# Generated by Django 4.1.1 on 2022-09-10 18:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orden',
            old_name='peso_prodcutos',
            new_name='peso_producutos',
        ),
        migrations.AddField(
            model_name='orden',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 9, 10, 18, 2, 45, 227852, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orden',
            name='tipo_paquete',
            field=models.IntegerField(choices=[(1, 'CHICO'), (2, 'MEDIANO'), (3, 'GRANDE'), (99, 'DEF')], default=99),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orden',
            name='estatus',
            field=models.IntegerField(choices=[(1, 'CHICO'), (2, 'MEDIANO'), (3, 'GRANDE'), (99, 'DEF')]),
        ),
    ]
