# Generated by Django 4.1.1 on 2022-09-11 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_peso_prodcutos_orden_peso_producutos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('coordenadas', models.CharField(max_length=255)),
                ('dirrecion', models.CharField(max_length=255)),
                ('numero_ext', models.CharField(max_length=255)),
                ('numero_int', models.CharField(max_length=255)),
                ('cp', models.IntegerField()),
                ('tipo', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='orden',
            name='estatus',
            field=models.IntegerField(choices=[(0, 'CREADO'), (1, 'RECOLECTADO'), (2, 'EN_ESTACION'), (3, 'EN_RUTA'), (4, 'ENTREGADO'), (5, 'CANCELADO')]),
        ),
    ]
