# Generated by Django 4.1.1 on 2022-09-11 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_direccion_alter_orden_estatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='direccion',
            old_name='dirrecion',
            new_name='direccion',
        ),
        migrations.AddField(
            model_name='orden',
            name='dirccion_destino',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='ordenDestino_Direccion', to='api.direccion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orden',
            name='dirccion_origen',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='ordenOrigen_Direccion', to='api.direccion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='direccion',
            name='numero_int',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'CLIENTE'), (2, 'TIENDA'), (3, 'PUNTO')]),
        ),
    ]
